//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public string Amount { get; set; }
        public Nullable<int> Eid { get; set; }
        public Nullable<int> Iid { get; set; }
    
        public virtual Entrepreneur Entrepreneur { get; set; }
        public virtual Investor Investor { get; set; }
    }
}
