//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Commnets = new HashSet<Commnet>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> eid { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Commnet> Commnets { get; set; }
        public virtual Entrepreneur Entrepreneur { get; set; }
    }
}
